user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 1024;
}

http {

        include /etc/nginx/mime.types;
        default_type application/octet-stream;
    
        server {
            listen 447 ssl;
            server_name asoumare.42.fr;

            ssl_certificate /etc/ssl/certs/nginx.crt;
            ssl_certificate_key /etc/ssl/private/nginx.key;

            root /home/asoumare/data;
            index index.php;

            location / {
                try_files $uri $uri/ /index.php?$args;
            }

            location ~ \.php$ {
                include fastcgi_params;
                fastcgi_pass wordpress:9000;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
